### ISSUE TITLE
Support for Ethernet/IP

### ISSUE THREAD

**Issue by Donnie-github** [RapidScada/scada#14]
Hi, 
Do you plan to support Ethernet/IP industrial protocol ?

thanks

**Comment by 2mik** [comment]
Hi,
As I understand, EtherNet/IP (Common Industrial Protocol) is a generic set of protocols. Could you provide more details about models of devices you use or plan to use?

**Comment by Bolkano** [comment]
I'm using Allen Bradley - Micro850. So I need a scada that support EtherNet/IP.

**Comment by 2mik** [comment]
Not yet. To connect your devices you could look for a OPC server, develop or purchase the appropriate driver for Rapid SCADA.
