### ISSUE TITLE
SIEMENS modbus card direct connection support

### ISSUE THREAD

**Issue by zealwebtech** [RapidScada/scada#17]
Hi,
Is that we can replace ADAM cponverter and can connect directly with SIEMENS modbus cards and devices for pooling the data?

**Comment by 2mik** [comment]
I think yes )

**Comment by zealwebtech** [comment]
Hi Mik,
I was testing it along with SIEMENS S7-415 PLC using SIEMENS PCS7 with Cp-341 over RS485 i was facing error like External error occured.
Can you have some manual or procedure?
I really wanted to impliment this with SIEMENS products.

**Comment by 2mik** [comment]
Hi,
Download the latest Rapid SCADA installation package from http://rapidscada.org/
In Doc folder there is a step by step manual describes how to set up Mobdus on Rapid SCADA.
Please provide the information about the error shown in SCADA-Communicator communication line log.
