### ISSUE TITLE
Seems not compatible with Silverlight latest version

### ISSUE THREAD

**Issue by zealwebtech** [RapidScada/scada#18]
Dear 2mik,
seems its not working with silverlight latest version.

**Comment by 2mik** [comment]
We are going to get rid of Silverlight. Unfertunately, Silverlight is a blind alley.

**Comment by 2mik** [comment]
Backward compatibility of the file format will be supported.

**Comment by 2mik** [comment]
If there is a problem to start displaying schemes, write to forum.rapidscada.org
