### ISSUE TITLE
Source build for non-Windows users

### ISSUE THREAD

**Issue by mcgiwer** [RapidScada/scada#22]
Please add files with would make posible to build the RapidScada sources for users of other Operating Systems then Windows

**Comment by 2mik** [comment]
What files do you mean?
You can read how to build the project using Mono Develop [here](http://forum.rapidscada.ru/?topic=%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-scadaserver-4-5-7-mono). Use a Google translator
