### ISSUE TITLE
SCADA - Коммуникатор: Ошибка при обзоре узла текущих данных

### ISSUE THREAD

**Issue by baur** [RapidScada/scada#27]
Получаю ошибку при попытке подключится к OPC серверу
**Ошибка при обзоре узла текущих данных**
на фоне видно текущие данные OPC сервера
![image](https://cloud.githubusercontent.com/assets/2898361/20616228/002e83de-b30b-11e6-9a7e-7d9089ac3d0d.png)

по факту к OPC серверу подключается, но не отображает текущие данные

![image](https://cloud.githubusercontent.com/assets/2898361/20616370/094c1232-b30c-11e6-9e8e-fd56d4ad7c9f.png)

**Comment by 2mik** [comment]
Ответил на форуме.
