### ISSUE TITLE
Projects Looks Interesting, is it possible to develop its view on Ios and Android 

### ISSUE THREAD

**Issue by abhishekricky** [RapidScada/scada#30]
Hi,

I was looking for possibilities, to have application also for ios and android, becoz tht would complete its cycle

**Comment by 2mik** [comment]
Hi,
Of course, it is possible to develop iOS and Android native applications for Rapid SCADA. Rapid SCADA has rich integration options: TCP, HTTP, DB. But such tasks currently not in our plans. If you decide develop these apps, I will provide necessary information.

**Comment by abhishekricky** [comment]
Hi,

Yes. I am planning to start it development will take Android application
first. Will create github repo .

About integration in 2 days, I will create roadmap and additional
information that is required

**Comment by 2mik** [comment]
Please ask in this forum http://forum.rapidscada.org/?forum=development-and-integration
