### ISSUE TITLE
Not able build using VS-2013

### ISSUE THREAD

**Issue by subu1979** [RapidScada/scada#35]
Hi Team,

As per the HowToBuild.txt file, i'm not able to build the project. Can you provide us the base solution(sln) file for the whole project. Also where is the following projects present.

1) OpenKPs
2) ScadaCommCommon

Request you to kindly do the needful.

Regards
Subramaniyam.KMV

**Comment by 2mik** [comment]
Hello,
What error messages did you receive during build?
Joining a lot of projects into a one solution significantly reduce the speed of Visual Studio,
[OpenKPs](https://github.com/RapidScada/scada/blob/master/ScadaComm/OpenKPs/OpenKPs.sln)
ScadaCommCommon is a part of [ScadaComm](https://github.com/RapidScada/scada/blob/master/ScadaComm/ScadaComm.sln)

**Comment by subu1979** [comment]
Hi,

Thanks for your information. I was able to build the project successfully.

Regards
Subramaniyam.KMV
