### ISSUE TITLE
ScadaWebCommon-UserData.cs : ServerComm.Roles is undefined

### ISSUE THREAD

**Issue by tamtrong** [RapidScada/scada#38]
Hi Everyone,
I am newbie to RapidScada, after downloading sourcecode and build the solution in order of HowToBuild.txt, when building ScadaWebCommon project which ref to ScadaData project, I found this error:
Error	CS0426	The type name 'Roles' does not exist in the type 'ServerComm'
Therefore, I checked ServerComm.cs of ScadaData project and found no property named "Roles"
I've download the latest version sourcecode until now.
Could somebody explain this? Many thanks

**Comment by 2mik** [comment]
Hi,
Some of the projects, including ScadaWebCommon,  are obsolete. We will clean then in the near future.
Build ScadaWebCommon5 and ScadaWebShell5. Skip: ScadaWebCommon, ScadaWebConfig, WebPageSample.

**Comment by 2mik** [comment]
Also skip ScadaWeb\OpenPlugins\PlgScheme

**Comment by tamtrong** [comment]
Thanks for your information, 2mik. RapidScada is really interesting to me.

**Comment by 2mik** [comment]
Thank you too ))
