### ISSUE TITLE
Adding a C# script engine

### ISSUE THREAD

**Issue by circler3** [RapidScada/scada#45]
## Ideas
Hi, thanks for this great project. A lot of scada systems contain script engines (e.g. VBA). I think script engine is very useful.

* Adding a script engine to the scada can help reduce the efforts on developing additional Mods.
* Formula can be replaced with more comprehensive C# script engine.

**Comment by 2mik** [comment]
Hi,
Could you explain your idea more detailed? What is the difference with the existing Rapid SCADA C# script engine?

**Comment by circler3** [comment]
Hi.
Differences from current formula engine in my mind:

* Support server side scripting (not only binding to input/output channels). Hence simple server Mod dlls can be replaced with scripts.
* Support code highlight and compile check.

**Comment by 2mik** [comment]
Hi,
When you use formulas, they are executed on server side. May be it should be a simple graphical tool for developing server modules?
You right about code highlighting and compile checking. Currently, I recommend develop complex formulas in Visual Studio based on the FormulaTester project https://github.com/RapidScada/scada/tree/master/ScadaServer/FormulaTester

**Comment by circler3** [comment]
Hi,
Yes, a simple graphical tool for developing server modules (or scripts) is good for someone who want to leverage the server-side events (such as OnServerStart) but do not want to open visual studio to build a dll.

**Comment by 2mik** [comment]
If somebody create the tool which implements intuitive script constructor, it would be great. The tool could generate a server module and add it to the server configuration. I'm not sure that my resources are enough for this task, because there are a lot of major features should be done.

**Comment by zcattacz** [comment]
A tool like https://dotnetfiddle.net/  ?

**Comment by 2mik** [comment]
Something like PLC graphical languages: Ladder Diagram, Function Block Diagram (FBD) and Sequential Function Chart (SFC).
https://en.wikipedia.org/wiki/Programmable_logic_controller
