### ISSUE TITLE
Building binaries

### ISSUE THREAD

**Issue by Zod20** [RapidScada/scada#53]
Hi I have built all the solutions successfully in the order shown in the howtobuild.txt. How to build the .exe now and in what order?

**Comment by circler3** [comment]
When you build all the projects, you will get all the necessary files (include .exe) in seperate solution output folders. You'd better try an installer release first to help you know more about the software.

**Comment by Zod20** [comment]
Thanks a lot, it works now! Everything seems to be working fine and it's a very well-written piece of software. Thank you for the hard work :)
