### ISSUE TITLE
The project files(.sln .csproj) should in git control?

### ISSUE THREAD

**Issue by lugreen** [RapidScada/scada#54]
I fork the project, there generated some new file and the  Solution file (.sln) and Project file(csproj) also changed  when i open the project  with vs2017.   It wil cause  merge conflict . How can i avoid the problem?
Blow is the screencapture. 
![image](https://user-images.githubusercontent.com/1725996/39079874-cf9e8abe-4555-11e8-8fb8-16f2db6dff63.png)

**Comment by circler3** [comment]
I think you have moved the solution file location of **log.sln**. If you keep the original folder structure, it won't show confict.

**Comment by lugreen** [comment]
Yes,you are right. 
It cased by  some operate by me. Now it is correct.

**Comment by lugreen** [comment]
Thanks very much.
