### ISSUE TITLE
New Kp Driver - How to include in Communicator List

### ISSUE THREAD

**Issue by mhanuel26** [RapidScada/scada#63]
Hello Mikhail,

I have so far worked with the KpTest modifying it to suit my needs but I want to release a first version and so I need to change the name of project and compile name. After doing it and copying the resulting file to the KP directory as I was already doing with KpTest, I cannot see the new KpWiznet under the list of drivers in communicator.
What am I doing wrong or missing?

Please let me know,

Thank you in advance,

**Comment by circler3** [comment]
Did you modify the class name of the KpTest? If you are working on new drivers, there is a instruction:
[https://rapidscada.org/device-drivers-development/](https://rapidscada.org/device-drivers-development/)
