### ISSUE TITLE
CalcEngine.cs file in log folder

### ISSUE THREAD

**Issue by fmarslan** [RapidScada/scada#65]
There is CalcEngine.cs in scada server log folder

**Comment by 2mik** [comment]
Please clarify your question

**Comment by fmarslan** [comment]
when I installed rapid scada by installer, The Scada server log folder contained the  CalcEngine.cs file. I think  The file should not be there.

**Comment by 2mik** [comment]
It's OK. This file is created by SCADA-Server and it is located in the Log folder, because it is created just for information.
