### ISSUE TITLE
Add a Register function

### ISSUE THREAD

**Issue by linkangsun** [RapidScada/scada#72]
I wonder if the project has a register function in Login page, I want to add a register page,the behind code,lies in the file "Register.asp.cs" which is I am about to edit of sub-project ScadaWeb, needs the interface,which is my obstacle, to access to database so that  I can check new user information and write it to database. I am not familiar with the API yet,So if it is possible to give me some clues to find the related API ? 0.0

**Comment by 2mik** [comment]
It's possible. You should:
1. Create your own database that contains user credentials.
2. Create a module for SCADA-Server that checks user login and password.
3. Create a plugin to manage users.
Let's continue discussing the details on https://forum.rapidscada.org  If you need help to register the forum, let us know by email.
