### ISSUE TITLE
turkish chracter issue

### ISSUE THREAD

**Issue by epoch79** [RapidScada/scada#8]
hi, I want to report a minor bug. 
When you click pass to server button on Admin application, the app creating "ınterface.dat" not the "interface.dat" in the C:\SCADA\BaseDAT directory. I think this is a lower case issue in Admin application on  "Tables" class's file name property.
public string FileName
            {
                get
                {
                    return Name.ToLower() + ".dat";
                }
            }

**Comment by 2mik** [comment]
Thanks! Could you give additional information:
1. Is the symbol 'ı' a letter of Turkish alphabet?
2. How this issue affects work of the software?

**Comment by 2mik** [comment]
I have fixed this issue in develop branch. Tell me, please, if it affects normal work, and I'll merge it to the distributive.

**Comment by epoch79** [comment]
yes "ı" is letter.
when you click pass to server button in basedat folder "ınterface.dat"  and "ıncnl.dat".
Changes on Admin app doesn't apply to server.

**Comment by epoch79** [comment]
i tried your fix and working good. thanks.
But i think you have to merge it to the distributive immediately.

**Comment by 2mik** [comment]
Done.
